### ISSUE TITLE
Keyboard shortcut to expand all gutter tooltips?

### ISSUE THREAD

**Issue by olivierlefloch** [vigo/textmate2-python-fmt#1]
Is there a keyboard shortcut to expand all gutter tooltips, to get the same output as in your `README` image? Thanks!

**Comment by vigo** [comment]
hmmm. I need to investigate if TextMate supports such a thing. Great idea by the way. Time saver. I'll try to implement that. Thanks

**Comment by vigo** [comment]
hey @olivierlefloch i made it! tried here: https://github.com/vigo/textmate2-ruff-linter will update this bundle too

**Comment by vigo** [comment]
use option+G (new release!)
